<?php 
	$url_new = $this->url(array('module'=>'sales','controller'=>'program','action'=>'add',));
	$url_edit = $this->url(array('module'=>'sales','controller'=>'program','action'=>'edit',));
	$url_delete = $this->url(array('module'=>'sales','controller'=>'program','action'=>'delete',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	$rs = $this->product;
?>
<title>កម្មវិធីបុណ្យ</title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("កម្មវិធីបុណ្យ");?>
				</div>
				<a href="<?php echo $url_new;?>" class="btn btn-bg blue  pull-right">
					<i class="fa fa-plus"></i>&nbsp;<?php echo $tr->translate("ADD_NEW");?>
				</a>
			</div>
			<div class="portlet-body form frmfilter">
				<form id="frm" method="post" autocomplete="off" action="<?php echo $formFilter->getAction(); ?>">
					<div class="form-group">
							<label class="control-label col-md-2">
								<?php echo $formFilter->getElement('ad_search');?>
							</label>
							<label class="control-label col-md-2">
								<?php echo $formFilter->getElement('branch');?>
							</label>
							<label class="control-label col-md-2">
								<?php echo $formFilter->getElement('start_date');?>
							</label>
							<label class="control-label col-md-2">
								<?php echo $formFilter->getElement('end_date');?>
							</label>
							<label class="control-label col-md-2">
								<?php echo $formFilter->getElement('status');?>
							</label>
							<label class="control-label col-md-2">
								<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-search"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
							</label>
						</div>				
				</form> 
				<div class="contain_form" style="clear: both;">
					<?php echo $this->list; ?>
				</div>
			    
		   </div>
		</div>
	</div>
</div>
<script>
var row=0;
var url="";
$(function(){	
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {		
			var m = "clicked: " + key;
			if(key=="edit"){
				url='<?php echo $this->baseUrl()."/sales/program/edit/id/";?>';
			}else if(key=="travel"){
				url='<?php echo $this->baseUrl()."/sales/program/travel/id/";?>';
			}else if(key=="copy"){
				url='<?php echo $this->baseUrl()."/sales/program/copy/id/";?>';
			}else if(key=="locationmong"){
				url='<?php echo $this->baseUrl()."/sales/program/locationmong/id/";?>';
			}
			
			gotoAction();
		},
		items: {
			"edit": {name: "កែប្រែ", icon: "edit", accesskey: "e"},
			"copy": {name: "copy", icon:  "copy", accesskey: "e"},
			"travel": {name: "វេលាកម្មវិធី", icon:  "fa-clock-o", accesskey: "e"},
			"locationmong": {name: "ព័ត៌មានផ្លាកម៉ុង", icon:  "fa-map-marker", accesskey: "e"},
			
			
		}
	});
});
function setrowdata(index){
	  row = index;
	}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}
</script>





















