<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$brach_name =  $this->branch;
?>
<title>Mong Construct Items Report</title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("របាយការណ៍សម្ភារៈសាងសង់ម៉ុង");?>
				</div>
					<div class="btn-group pull-right">
						 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
						   Actions <i class="fa fa-angle-down"></i>
						 </button>
						<ul class="dropdown-menu" role="menu">
							<li>
								<a href="#" onclick="doPrint();">
									<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
								</a>
							</li>
							<li>
								<a href="#" onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
							</li>
						</ul>
				 </div>
			</div>
			
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
		<style>
			.style{
				line-height: 25px;font-size: 12px !important;
				font-family: 'Khmer OS Battambang';
			}
			ul{margin: 0;padding:0;}
			table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
			th{padding: 5px;}
			.hover:hover{background: #ccc;}
			table { page-break-inside:auto }
			tr{ page-break-inside:avoid; page-break-after:auto; }
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			}
		</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
			            	<tr>
			                	<td align="center" width="16%" valign="top"><img  height="95px" src="<?php echo $this->baseUrl();?>/images/logosbona.jpg"></td>
		                	<td width="70%" valign="top">
			                		<ul>
			                			<li style="text-align:center; font-size:16px; font-family:'Khmer OS Muol Light'; color:red !important"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
			                			<li style="text-align:center; font-size:15px; font-family:'Khmer OS Muol Light'; color:red !important"><?php echo $tr->translate("របាយការណ៍សម្ភារៈសាងសង់ម៉ុង់");?></li>
			                		</ul>
			                	</td>
			                    <td width="20%"></td>
			                </tr> 
		            	</tbody>
		            </table>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" id="exportExcel">
		            <table align="center" width="100%">
						<tr style="font-size: 14px;">
							<td width="70%">
								<table align="center" width="100%" style="margin-left:15px;white-space:nowrap;">
									<tr style="font-size: 14px;">
										<td width="15%">
											វិក័យបត្រ
										</td>
										<td width="60%" style="font-weight:bold;">
											: <?php echo $this->monginfo['invoice_no'] ?>
										</td>
										<td width="25%">
										</td>
									</tr>
									<tr style="font-size: 14px;">
										<td >
											ឈ្មោះអតិថិជន
										</td>
										<td style="font-weight:bold;">
											: <?php echo $this->monginfo['cust_name'] ?>
										</td>
									</tr>
									<tr style="font-size: 14px;">
										<td >
											លេខទូរស័ព្ទ
										</td>
										<td style="font-weight:bold;">
											: <?php echo $this->monginfo['cus_phone'] ?>
										</td>
									</tr>
									<tr style="font-size: 14px;">
										<td >
											ទីតាំងបុណ្យ
										</td>
										<td style="font-weight:bold;">
											: <?php echo $this->monginfo['place_bun'] ?>
										</td>
									</tr>
								</table>
							</td>
							<td width="30%">
								<table align="center" width="100%" style="white-space:nowrap;">
									<tr style="font-size: 14px;">
										<td width="30%">
											ជាងសាងសង
										</td>
										<td width="70%" style="font-weight:bold;">
											: <?php echo $this->monginfo['name'] ?>
										</td>
									</tr>
									<tr style="font-size: 14px;">
										<td >
											ភេទ
										</td>
										<td style="font-weight:bold;">
											: <?php echo $this->monginfo['sex'] ?>
										</td>
									</tr>
									<tr style="font-size: 14px;">
										<td >
											លេខទូរស័ព្ទ
										</td>
										<td style="font-weight:bold;">
											: <?php echo $this->monginfo['phone'] ?>
										</td>
									</tr>
									
								</table>
							</td>
						</tr>
					</table>
					<table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <thead>
			                <tr bgcolor="#b0bdfd" align="center" style="font-weight:bold; line-height: 28px; font-size:14px; padding:1px 0px; white-space: nowrap; ">
			                    <td>&nbsp;<?php echo $tr->translate("NUM");?></td>
								<td>&nbsp;<?php echo $tr->translate("សម្ភារៈ");?></td>
								<td>&nbsp;<?php echo $tr->translate("តម្លៃរាយ");?></td>
								<td>&nbsp;<?php echo $tr->translate("បរិមាណ");?></td>
								<td>&nbsp;<?php echo $tr->translate("សរុប");?></td>
			                </tr>
		                </thead>
		                <tbody>
		                <?php $i=0;$total=0; $count = count($this->mong_detail);
		                if(!empty($this->mong_detail)){foreach ($this->mong_detail AS $index => $rs){$i++;?>
						<tr class='hover' style="border:1px solid #000;font-size:13px;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $i;?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["title"];?></td>
						   <td align="center" style="font-family: 'Open Sans', sans-serif;font-weight: bold;">&nbsp;<?php echo "$ ".number_format($rs["item_price"],2);?></td>
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $rs["item_qty"];?></td>
						   <td align="center" style="font-family: 'Open Sans', sans-serif;font-weight: bold;">&nbsp;<?php echo "$ ".number_format($rs["item_total"],2);?></td>
						</tr>
						   
                    	<?php $total=$total+$rs["item_total"];}}?>
						<tr class='hover' style="border:1px solid #000;font-size:14px;">
						   <td colspan="4" align="right" height="40px" style="font-weight:bold;">តម្លៃសរុប  &nbsp;</td>
						   <td style="font-family: 'Open Sans', sans-serif;font-weight: bold;">&nbsp;<?php echo "$ ".number_format($total,2);?></td>
						</tr>
		                </tbody>
		           </table>
	               <br>
	               <table align="center" width="100%">
					   <tbody>
					   		<tr style="font-size: 14px;">
						        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
					   		</tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
</script>
